version: '2'
services:
    base-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/base/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=base
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
